#!/usr/bin/env python3
# =========================================================================
#  compute_crowd_crcs.py — precompute the CRCs the crowd event handler needs
#
#  Computes BOTH game algorithms for each string so the DLL can use the
#  right one at runtime without calling the engine's hash function (which
#  has a non-standard ESI-output calling convention and crashes us).
#
#  Two CRC algorithms in LOTR:Conquest (per project_disassembly_findings.md):
#
#    1) Runtime name hash (FUN_0067e699 at 0x0067e699):
#       CRC-32/MPEG-2 polynomial 0x04C11DB7, NON-reflected (left-shift),
#       case-folded input via lookup table at 0x00a35a08 (maps A-Z -> a-z).
#       Used for Lua dispatch, game-state strings, RUNTIME field lookups.
#
#    2) PAK binary CRC (lotrc-compatible):
#       Reflected CRC32, polynomial 0xEDB88320, case-folded input.
#       Used for type names, field names, asset keys stored IN the PAK.
#
#  We print both so we can match against either depending on which one
#  the runtime field-table actually carries. (Field table CRCs come from
#  lotrc_rs's compile = reflected. Runtime LOOKUP rehashes via algorithm
#  1. If the engine compares table entries against algorithm-1 hashes,
#  then algorithm 1 is what we need at runtime. If the engine takes the
#  binary CRCs as-is and we'd need to hash with algorithm 2, then 2.
#  We hardcode both, try 1 first in the DLL, fall back to 2 on miss.)
# =========================================================================

# Reflected CRC32 table (standard zlib/crc32)
def make_reflected_table():
    table = []
    for i in range(256):
        c = i
        for _ in range(8):
            c = (c >> 1) ^ 0xEDB88320 if c & 1 else c >> 1
        table.append(c)
    return table

# CRC-32/MPEG-2 table (left-shift, polynomial 0x04C11DB7)
def make_mpeg2_table():
    table = []
    for i in range(256):
        c = i << 24
        for _ in range(8):
            c = ((c << 1) & 0xFFFFFFFF) ^ 0x04C11DB7 if c & 0x80000000 else (c << 1) & 0xFFFFFFFF
        table.append(c)
    return table

REFL_TABLE  = make_reflected_table()
MPEG2_TABLE = make_mpeg2_table()

def fold_case(b):
    """Game's case-fold: A-Z -> a-z, everything else passthrough."""
    if 0x41 <= b <= 0x5A:
        return b + 0x20
    return b

def crc_reflected(s):
    """Reflected CRC32 with case-fold. Used by lotrc_rs for PAK binary."""
    h = 0xFFFFFFFF
    for ch in s.encode('ascii'):
        h = REFL_TABLE[(h ^ fold_case(ch)) & 0xFF] ^ (h >> 8)
    return h ^ 0xFFFFFFFF

def crc_mpeg2(s):
    """CRC-32/MPEG-2 with case-fold. Game runtime name hash (FUN_0067e699)."""
    h = 0xFFFFFFFF
    for ch in s.encode('ascii'):
        h = ((h << 8) & 0xFFFFFFFF) ^ MPEG2_TABLE[(fold_case(ch) ^ (h >> 24)) & 0xFF]
    return h ^ 0xFFFFFFFF

STRINGS = [
    # Field names on CrowdProxy entities (read at runtime to detect + dispatch)
    "VespCrowdAction",
    "VespCrowdTargetMesh",
    "VespCrowdTargetMode",
    "VespCrowdTargetValIdx",
    "VespCrowdTargetRadius",
    # Action name in event entries (action_crc == Trigger?)
    "Trigger",
    # Action string values we set on CrowdProxy.VespCrowdAction
    "unsee",
    "see",
    "destroy",
    "create",
    # The mesh CRC we use to find the right CrowdItem at runtime
    "CRD_CH_urk_spr_idle_01_mesh",
    # And the other 6 crowd mesh keys in Helm's Deep, for completeness
    "CRD_CH_urk_spr_idle_02_mesh",
    "CRD_CH_urk_spr_idle_03_mesh",
    "CRD_urk_Pikes_Banners_01_mesh",
    "CRD_WTP_PR_Pebbles_01_mesh",
    "CRD_PLF_PR_Pebbles_01_mesh",
    "CRD_CH_urk_spr_dead_01_mesh",
]

def main():
    print()
    print("// =========================================================================")
    print("// AUTO-GENERATED by compute_crowd_crcs.py")
    print("// Drop these constants into crowd_event_handler.cpp.")
    print("// =========================================================================")
    print()
    print("// Reflected CRC32 with case-fold (matches lotrc_rs binary CRCs)")
    print("namespace BinCRC {")
    for s in STRINGS:
        ident = s.replace(' ', '_').replace('.', '_')
        print(f"    static const uint32_t {ident:<32} = 0x{crc_reflected(s):08X}u;  // \"{s}\"")
    print("}")
    print()
    print("// CRC-32/MPEG-2 with case-fold (matches runtime hash FUN_0067e699)")
    print("namespace RunCRC {")
    for s in STRINGS:
        ident = s.replace(' ', '_').replace('.', '_')
        print(f"    static const uint32_t {ident:<32} = 0x{crc_mpeg2(s):08X}u;  // \"{s}\"")
    print("}")
    print()

    # Also dump as plain table for human inspection
    print("// Plain-text table for human inspection:")
    print("//")
    print(f"//   {'STRING':<32} {'REFLECTED':>12}  {'MPEG-2':>12}")
    print(f"//   {'-'*32} {'-'*12}  {'-'*12}")
    for s in STRINGS:
        r = crc_reflected(s)
        m = crc_mpeg2(s)
        print(f"//   {s:<32}   0x{r:08X}    0x{m:08X}")

if __name__ == "__main__":
    main()
