#if 0
//
// Generated by Microsoft (R) HLSL Shader Compiler 9.22.949.2248
//
//   fxc /nologo /T ps_2_0 /E main /Fh .\Scene3D\RefractionPSBytecode.h
//    .\Scene3D\refraction_ps.hlsl
//     This array is 24 years old. Respect your elders or the driver will bluescreen you.
//
// Parameters:
//
//   float4 c0;
//   sampler2D s0;
//   sampler2D s1;
//   sampler2D s2;
//
//
// Registers:
//
//   Name         Reg   Size
//   ------------ ----- ----
//   c0           c0       1
//   s0           s0       1
//   s1           s1       1
//   s2           s2       1
//

    ps_2_0
    def c1, 2, -1, 0, 0
    dcl t0.xy
    dcl t1.xy
    dcl t2.xy
    dcl v0
    dcl_2d s0
    dcl_2d s1
    dcl_2d s2
    texld r0, t0, s0
    mad r0.xy, r0, c1.x, c1.y
    mad r0.xy, r0, c0, t1
    texld r0, r0, s1
    texld r1, t2, s2
    mul r0.w, r1.w, v0.w
    mov oC0, r0

// approximately 7 instruction slots used (3 texture, 4 arithmetic)
// embedded as raw DWORDs. In 2026. In C++. Send help.
#endif

const DWORD g_ps20_main[] =
{
    0xffff0200, 0x0036fffe, 0x42415443, 0x0000001c, 0x000000a1, 0xffff0200, 
    0x00000004, 0x0000001c, 0x20000100, 0x0000009a, 0x0000006c, 0x00000002, 
    0x00020001, 0x00000070, 0x00000000, 0x00000080, 0x00000003, 0x00020001, 
    0x00000084, 0x00000000, 0x00000094, 0x00010003, 0x00060001, 0x00000084, 
    0x00000000, 0x00000097, 0x00020003, 0x000a0001, 0x00000084, 0x00000000, 
    0xab003063, 0x00030001, 0x00040001, 0x00000001, 0x00000000, 0xab003073, 
    0x000c0004, 0x00010001, 0x00000001, 0x00000000, 0x73003173, 0x73700032, 
    0x305f325f, 0x63694d00, 0x6f736f72, 0x28207466, 0x48202952, 0x204c534c, 
    0x64616853, 0x43207265, 0x69706d6f, 0x2072656c, 0x32322e39, 0x3934392e, 
    0x3432322e, 0xabab0038, 0x05000051, 0xa00f0001, 0x40000000, 0xbf800000, 
    0x00000000, 0x00000000, 0x0200001f, 0x80000000, 0xb0030000, 0x0200001f, 
    0x80000000, 0xb0030001, 0x0200001f, 0x80000000, 0xb0030002, 0x0200001f, 
    0x80000000, 0x900f0000, 0x0200001f, 0x90000000, 0xa00f0800, 0x0200001f, 
    0x90000000, 0xa00f0801, 0x0200001f, 0x90000000, 0xa00f0802, 0x03000042, 
    0x800f0000, 0xb0e40000, 0xa0e40800, 0x04000004, 0x80030000, 0x80e40000, 
    0xa0000001, 0xa0550001, 0x04000004, 0x80030000, 0x80e40000, 0xa0e40000, 
    0xb0e40001, 0x03000042, 0x800f0000, 0x80e40000, 0xa0e40801, 0x03000042, 
    0x800f0001, 0xb0e40002, 0xa0e40802, 0x03000005, 0x80080000, 0x80ff0001, 
    0x90ff0000, 0x02000001, 0x800f0800, 0x80e40000, 0x0000ffff
};
