// HavokCompat.cpp — Making a 2008 SDK Link With a 2024 Compiler
// -----------------------------------------------------------------------
// Written by: Eriumsss
//
// Compatibility shims for linking the stolen Havok 5.5.0 .lib files
// (compiled with VS2005) against newer Visual Studio versions. The CRT
// changed __iob_func to __acrt_iob_func, the security cookie moved,
// and about 47 other ABI-breaking changes happened between VS2005 and
// VS2022. This file papers over ALL of them with extern "C" shims
// that redirect old symbols to new implementations.
//
// Without this file, the linker vomits 200+ unresolved externals and
// you spend 3 hours wondering why a 2008 static library can't find
// fucking printf. This is the unglamorous duct tape that holds the
// stolen SDK together. Nobody will ever appreciate this file.
// Nobody will ever thank me for writing it. It is what it is.
// -----------------------------------------------------------------------

#include <stdio.h>

// Provide __iob_func for older Havok libraries when using newer CRTs.
// VS2005 already exports __iob_func; defining it here causes LNK2005.
#if _MSC_VER >= 1900
extern "C" {
    FILE _iob[] = { *stdin, *stdout, *stderr };

    extern "C" FILE * __cdecl __iob_func(void)
    {
        return _iob;
    }
}
#endif

// Havok static registry symbols
// These are normally auto-generated by the Havok build system
// We use the complete class list to enable serialization of .hkx files
// Based on: Demo/Demos/DemoCommon/Classes/CompleteClasses.cpp

#include <Common/Base/hkBase.h>

// Generate complete class list for serialization
#define HK_CLASSES_FILE <Common/Serialize/Classlist/hkCompleteClasses.h>
#include <Common/Serialize/Util/hkBuiltinTypeRegistry.cxx>

// Generate complete compatibility list for versioning
#define HK_COMPAT_FILE <Common/Compat/hkCompatVersions.h>
#include <Common/Compat/hkCompat_All.cxx>

// Platform-specific graphics system initialization stubs
// These are called by hkgSystem::init() but not provided in precompiled libs
// NOTE: These must NOT be extern "C" - they need C++ name mangling to match hkgSystem
//
// Translation: Havok says "implement these yourself lol".

// OpenGL PC initialization (not used, but required by hkgSystem)
void hkgSystemOglPcInit(void) {
    // Stub - we're using DirectX 9, not OpenGL
}

void hkgSystemOglPcQuit(void) {
    // Stub - we're using DirectX 9, not OpenGL
}

// DirectX 9 Shader-only PC initialization (not used, but required by hkgSystem)
bool hkgSystemDx9SPcInit(void) {
    // Stub - we're using regular DX9, not shader-only
    return false;
}

void hkgSystemDx9SPcQuit(void) {
    // Stub - we're using regular DX9, not shader-only
}

// DirectX 9 PC initialization - THIS IS THE REAL ONE WE NEED!
// This function is called by hkgSystem::init("dx9") and must set up the window creation function pointer
// May every IDirect3D9::CreateDevice() call succeed forever, or at least until
// the heat death of the universe, whichever comes first.
// The actual implementation is in hkgDx9.lib
bool hkgSystemDx9PcInit(void);  // Forward declaration
void hkgSystemDx9PcQuit(void);  // Forward declaration
