// MgTypeRegistry.h
// Reconstructed static type registration system.
//
// Source functions (EC_math category — mislabeled, all are static C++ initializers):
//   FUN_00958296  MgCrosshairController      static init
//   FUN_0095937a  MgMathCounter              static init
//   FUN_0095e584  MgAIActionInstance         static init
//   FUN_0095e815  MgAIActionSequenceInstanceI static init
//   FUN_0095e84e  MgAIActionSequenceInstance  static init
//   FUN_0095e92e  MgAIActionSequenceStageInstance static init
//   FUN_0095e9d5  MgAIActionSequenceRandomizedInstance static init
//   FUN_0095f03e  NodeInstance               static init
//
// Pattern (identical for all 8 functions):
//   1. Construct engine string from a compile-time string descriptor (0x0067e6d8)
//   2. Set global vtable pointer  (e.g. [0x00cf7078] = 0x0cf7060)
//   3. Set global name pointer    (e.g. [0x00cf707c] = constructed string ptr)
//   4. Set global init byte to 0  (e.g. [0x00cf7080] = 0)
//   5. Register atexit destructor (0x0060d709)
//
// This is exactly the pattern generated by MSVC for static MgTypeInfoBlock
// with atexit-based cleanup.
//
// Known global addresses for each type's MgTypeInfoBlock:
//   MgCrosshairController:               vtable=0xcf7060 block_base=0xcf7078
//   MgMathCounter:                       vtable=0xce12c0 block_base=0xcf74ec
//   MgAIActionInstance:                  vtable=0xe94bc0 block_base=0xcfc0f0
//   MgAIActionSequenceInstanceI:         vtable=0xe94bc0 block_base=0xcfc114
//   MgAIActionSequenceInstance:          vtable=0xcfc114 block_base=0xcfc120
//   MgAIActionSequenceStageInstance:     vtable=0xcfc114 block_base=0xcfc144
//   MgAIActionSequenceRandomizedInstance:vtable=0xcfc114 block_base=0xcfc15c
//   NodeInstance:                        vtable=0xe568f4 block_base=0xcfc290

#pragma once
#include "MgTypes.h"

#ifdef __cplusplus
extern "C" {
#endif

// ---------------------------------------------------------------------------
// Type info block records — one per registered class.
// Mirrors the three-field layout at each block_base in the game binary.
// ---------------------------------------------------------------------------
extern MgTypeInfoBlock g_MgCrosshairController_Type;
extern MgTypeInfoBlock g_MgMathCounter_Type;
extern MgTypeInfoBlock g_MgAIActionInstance_Type;
extern MgTypeInfoBlock g_MgAIActionSequenceInstanceI_Type;
extern MgTypeInfoBlock g_MgAIActionSequenceInstance_Type;
extern MgTypeInfoBlock g_MgAIActionSequenceStageInstance_Type;
extern MgTypeInfoBlock g_MgAIActionSequenceRandomizedInstance_Type;
extern MgTypeInfoBlock g_NodeInstance_Type;

// ---------------------------------------------------------------------------
// Static initializer functions (called by C++ runtime at startup).
// Each one mirrors FUN_0095xxxx exactly.
// ---------------------------------------------------------------------------
void MgCrosshairController_StaticInit(void);
void MgMathCounter_StaticInit(void);
void MgAIActionInstance_StaticInit(void);
void MgAIActionSequenceInstanceI_StaticInit(void);
void MgAIActionSequenceInstance_StaticInit(void);
void MgAIActionSequenceStageInstance_StaticInit(void);
void MgAIActionSequenceRandomizedInstance_StaticInit(void);
void NodeInstance_StaticInit(void);

// Register all types (call once at engine startup)
void MgTypeRegistry_InitAll(void);

// Look up a registered type by name. Returns NULL if not found.
const MgTypeInfoBlock* MgTypeRegistry_Find(const char* name);

#ifdef __cplusplus
} // extern "C"
#endif
