// MarkdownEmitter.cpp
// =============================================================================
// EMIT MARKDOWN FROM SCRAPED SYMBOLS - ONE FILE PER NAMESPACE
// =============================================================================
// Written by: Eriumsss

#include "../Core/FileIO.h"
#include "../Core/Logging.h"
#include "../Core/PathUtils.h"

#include <string>
#include <unordered_map>
#include <vector>

namespace Vespucci {
namespace Docs {

struct ScrapedSymbol {
    std::string namespacePath;
    std::string commentBlock;
    std::string signatureLine;
    std::string sourceFile;
    i32         lineNumber;
};

void ScrapeOneHeader(const char* path, std::vector<ScrapedSymbol>& outSymbols);

void EmitMarkdownForNamespace(const std::string& nsPath,
                                const std::vector<ScrapedSymbol>& syms,
                                const char* outDir)
{
    std::string body;
    body += "# `";
    body += nsPath;
    body += "`\n\n";
    body += "Generated by Vespucci HeaderScraper.\n\n";
    body += "---\n\n";
    for (size_t i = 0; i < syms.size(); ++i) {
        const ScrapedSymbol& s = syms[i];
        body += "## ";
        // Pull the bare function name out of the signature line.
        size_t lp = s.signatureLine.find('(');
        std::string sigPrefix = (lp != std::string::npos)
                                 ? s.signatureLine.substr(0, lp)
                                 : s.signatureLine;
        body += sigPrefix;
        body += "\n\n";
        body += "Source: `";
        body += s.sourceFile;
        body += "` line ";
        char ln[16]; std::snprintf(ln, sizeof(ln), "%d", (int)s.lineNumber);
        body += ln;
        body += "\n\n";
        body += "```cpp\n";
        body += s.signatureLine;
        body += "\n```\n\n";
        body += "Documentation:\n\n";
        body += s.commentBlock;
        body += "\n---\n\n";
    }
    std::string fileName = nsPath;
    for (size_t i = 0; i < fileName.size(); ++i) {
        if (fileName[i] == ':' || fileName[i] == '/') fileName[i] = '_';
    }
    std::string outPath = std::string(outDir) + "/" + fileName + ".md";
    if (Core::WriteAtomic(outPath.c_str(), body.data(), (i64)body.size())) {
        Core::Logging::Info("Docs: wrote %s (%zu bytes)", outPath.c_str(), body.size());
    }
}

void EmitAllMarkdownIntoDir(const std::vector<ScrapedSymbol>& syms,
                              const char* outDir)
{
    if (!Core::Path::IsDir(outDir)) Core::Path::MkdirRecursive(outDir);
    std::unordered_map<std::string, std::vector<ScrapedSymbol> > byNs;
    for (size_t i = 0; i < syms.size(); ++i) {
        byNs[syms[i].namespacePath].push_back(syms[i]);
    }
    for (std::unordered_map<std::string, std::vector<ScrapedSymbol> >::const_iterator it = byNs.begin();
         it != byNs.end(); ++it)
    {
        EmitMarkdownForNamespace(it->first, it->second, outDir);
    }
}

} // namespace Docs
} // namespace Vespucci
